language: php

php:
  - 7.1

node_js:
  - "4"


before_script:
  - composer self-update
  - composer install
  - yarn

script: phpunit --bootstrap vendor/autoload.php --colors=always core/Tests/ && gulp

notifications:
    email: false

cache: yarn